apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-landing-page
  labels:
    app: auto-landing-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-landing-page
  template:
    metadata:
      labels:
        app: auto-landing-page
    spec:
      containers:
      - name: auto-landing-page
        image: harbor.gambiarras.website/automate/auto-landing-page:v1
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: secret-volume
          mountPath: /secrets
          readOnly: true
        - name: writable-keys
          mountPath: /app/config/keys
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: MONGO_URI   
      volumes:
      - name: secret-volume
        secret:
          secretName: auto-landing-page-secrets
          optional: true
      - name: writable-keys
        emptyDir: {}           
---
apiVersion: v1
kind: Service
metadata:
  name: auto-landing-page
  labels:
    app: auto-landing-page
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: auto-landing-page
---
apiVersion: v1
kind: Secret
metadata:
  name: auto-landing-page-secrets
type: Opaque
data:
  OPENROUTER_API_KEY: c2stb3ItdjEtOWIzYWNkMzk5YmQ4Y2MwZGIxYTFhOWRjNTAzMWQ3Yzk2NmRjNGQ3Y2M1YzdkYzA4NjgyYjJmZmRkMTE1YmEzNA==
  private.pem: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS0FJQkFBS0NBZ0VBcXVHQU1ISGk0bHBjRHllNjdPWWhkaUJEd0dnWGVCL2dOSUVxUkVtVys2VHpZNGcyCm9ia0VuckFFRlZuM3RhVDJITEZwSWNXUnBlaFF1SzZlNTNWdFNBYlgySXFMVE1ZNHZHeEdZdVhyNnpsejVXL3oKTitDa3RxVkVvZkZBNnZORXhnMUlERWRoUWV5MW9XR2tpSCtrRlVGeUozb2l6RitCbE1pU1lmNENjVitSeE5SSgozcTJFTVJ6dE5yWm1HR2VwRHowQlRXWDhKaXNpd0k1Z0xsTm5OcVVydnEyU3hpNVE2QUtCcHczWVF0dCtwUWNJCkVuY0thZVQ3cmxEN2FwM1h4bHduRTc2cWtUdC84Z3U0QjBTcVUrWFhIS3BadlJrV3hnTXFwcFZQT09saGo2ZEwKME8wNnBQMXo5VXFaSWVMNTJNVlNjRTJwemNmcytLcHZwdjQ3dEV5eHlsM1lXdEQxZUlTRk5Sb0YzL3ZlMTd2YwpVM2hEVUdLNUVrYzl4b2dWYkR0b0NCcHB4WVFSWGJmZVV2b1lyKzdaZ2g0UFl4eXhoMVMzWkxBemJkWllvaDdVCjVkRG9NZUVtaFpqdGwxNE8zZS9EaDQ0R0IvWktiVkFHVkwrRFFIZEVRWHZjZWlqenpvbEh3YXh2WlVONHBVM0kKWVpmaUl3bm9lT1YxYjhZUnA1d0l3UlE3OUtMQjIrOW9JcmV0Y1pMN0pXVkZPL0dvZlZTMkZNUkV4R2MwNHRJRQpkSkhXMzlHbnQzb3ZWUTh0djZjSVhpY3hkTTRpaUdYeSthQ0twWnE1WHVaeGhYNExNeEt1TlRRUlN6WXFDZCt0Ci9vV2ZwbWVqOE1ydjZXcFE4cFdJSW5jblhSdXR1WUQrU1d5a1gwWjlHcWNEVExrRlZmZkRBc1hXRjY4Q0F3RUEKQVFLQ0FnQlJrOXYxeExqUzVONWtJY3g4UWhVaFpwL1JvQi9zS2hPSUhVM0hVZlp4WmpzSGZrVE9paHhwZ1pCQgpmVFRqazhBbXpJOXJIdjI4WFo4RHUrR0NrQzIrbi8yMWs5YVNyV0x5bVNJMUhweTFMRFZuQ0QzdHBDSWVTK0hyCkNkaTdFYTM0ZXVpMWEvSkRYYlVNT1NncVBmMWdaR0VSOVozZFFZOEVMNGlxblhBZkhjZmlWcEo1YXc3YnYzcUQKanlwSVpseHdPT2lCUWJuUm92QXhTd2NodHBGa3BnK3ZOUUFIK3A2SFZJTCs5SDRVMU9LdCtDQmphRThoWkw2Kwpaa3pRaGxBM2sxRFlmVUxDbU13cENtMHRreHRaZURWc3F1cXlldUxEWDBtaVEwK1IxT0ROaXNtSUVXalkwV0xsCmJGcVVzZDRqSFhpUXdwTFkrYVBveHIwTTFQdzgrODF6Y2h1WC9JQ24rOW03Z0w1NHYyK0htZzhhVHMvT0kvTmIKWmNHTnJDZ3prY3ZabkV1Q08wMEJRNGQzbEZHdE9iQVpYeTJxMDlCLzVsLytmekkxNFpSRGYrSTh4K1ZGN2xmMgp6czFraytOSkliUkJoeWVNMFVqeVBRZ1JEOW15am05Vk5DRnl6eWYySE0vOU96SFpBRXo0Wm83ZVF5M0JkQk5VCkMvMndrbnhKV0t0K0hzOFppTHZYOGdSRTNIcmZhbytCaDdUcU9jeHBBWmlMb1JKbDRCemYvdkdVVkFJV0taTTQKaEN1RTE2VWRBQmw4RG85eWI2REQvbDRtTVdEYnBuVlZUVzI0N2RGVTNIOVREQW1lUCs1NzJBTW1MWVM4NVR5NQp1RHRGZjBIMG5FcVBaQzV6Q3BaRVpIWjA5RE8vbVl4N3ZjUHlmR0xNc2dYUHVwakxPUUtDQVFFQTRTd2tsMWRKCnFxMVpTakU3MXBaTWh2cUgxMXA5bGRKQkd4UE5YVzBnbHAwRGI2c2JTMlFiRWJtMDlCZ3lnUTdoaVVJaG5oYSsKQ3FqNHRjNkp6U2xMdzFUcDZ2dmw5Q3Ywd0psRHVFcEgxT2xZd3p3ZzBpN0VSWWh6MGxGa0QvQjljclVMdnNFZwpuTi9YWFpzZVUrU3h4Vlk0Yytmc0VxWXhpUXkwRXFORHNRZXVnQ1lKUllQbzNIanU5NDNESEhxTzhsQ09ZMWt6CjV6cGpyb3hCMmc4S0tvMnZLelFrZEFGdWtMVCsrbEZYWmMrMkJWNVMwRFFaczNZYmRJSllsa09ZL0pESWZlaTgKU0pWZU1EcWtwNC94bG9zZklDUklqMHhRNjd3TG1aZTExUGYzUDZIYlphOXExdHN1Ny9iWHQvMVJoaExqSkQyWQptS1NPRFdFdWdxMTBJd0tDQVFFQXdrYUxKVVY1ZFBVa0pDb2FGa0x5RmZkeEtEWEZDOGt6TDVQTUQwWW91VGZOCjF0aWNVNGFJYlJoNm5zemVRVTUxcGdRazJUdFd1cUt1ZFlwcWM4RWREMnZhN1ZPU3dBRzdpZkRaNkNHY0dHZFMKZkE3TTROMTl5MTVYcTIxVDYrMlExYWpJV0hlZE1ZOFhPeEtZOWdTWGFPam43dXRrWU14VTJyZnB0d2Nmbm55UgpWMWtKTStJYnc1OWR3UnA1aFl6d3pkTS9QZ2FQRzhlUk0yYmxFeGFteUl4VWhYMmFtbjcrc0ErUUJzMG16UWpPCkxWVVQ4R1ZOMHQwcG1nTEN0TDlXVkdVbnE3NWVkMVY5VWFHVDErWmJ2eFY5Ry8xc2FnUVRuL0dmMlJjV3dMWEwKZWFXS3NHRG5OTC8xbkJmQm05YUpqQzJvUEl2Smd5Y1A3Zlk3Mk5tUkJRS0NBUUIrcm40Ym95RXY0LzBUTDZYUgpzWmQyYlNiVnN2UnF3UEtlRUVMKzUvRm9xd2VPNEw0bmFUZU5mbVJlMitvMkQ3QTFyNzRJR2hWckcrdHBKYjBECmJ0TlFIc3JIeUZaMFMvS1VGT1l6blo3U0cwSXovUFVlS3UrRGl5UldWREl1Z1llaWJGY2lSN2RZYXRyWXIvZWQKRFZJeWlyS1NDdzRXNCtlRWltQVpDRCtDTHFjdk03Y05wQXZ6VmhwanJoN3lPOFdHY0duYlhRbEZjdVU0QTNMZApBbzhlcDczQVdjS1VmV1crQmdaWndEK2lhUHlvQW93bTFOa016VXJlL3FKbVQ3dVhoTUUzalNPNDFrZzZiQlBNCnJjQW1pVGpHdFlNWkU3K0hFTEdhQk85bzFPVUdxTUl0Y0VaMGdMWGtqWVNKMy92b3FXR2ZOd1JPQkc1aStxVFgKSWt6dkFvSUJBSDhPUGNCUmNINlNPR0hDZXk4bDkwZHdmYnZyZG9RZndPOFR2UGdjVFZQYzhDemJtMWx3K2RaSApsU0k0SC84Yi9ndG1XR2NOek1uZ3pUSW9KVGl4Q24xa2IxaVpPTGVFS28rclNnZnJ1emVta3laNVUzcVl3TVY1ClhPTExiSUEyN1dzZXFIQmJRaDRBVkJRWk5KcHBKRkREU2JSU2xHSk9JQXl2RFJYYmZjMWI4SDNzeC96N21tYlUKMmk4SlRvS09TNHFBNXJKOC9ha1FXcUVBWVQ2YnFOWXVHTFQ1RVZ5TFE2d0hjWTFSTEZnWnN5V29wNUtuM2o3Uwp6M3RlNU5IcTlOM2JEaGZmTjg3WnhVelczR2J0ekFEclg5Z25aSGp0VTV4ZUhNbVF0UnV4aVhKMFZvREZ6MUFMClh1a0lER0lMN0FjV2NSbXYza2w5Q1lqNmFlZUhXclVDZ2dFQkFJUzBDTmdkQ1RERWx1TjRqOTNtYW1QbTZONGYKNk5ISm1FTVUxZFFtWElHUXZlY1dCL3Y3dnh0S2tBV2RtdDE4UkUwMVhQQXVqTk1RZk9qWGZtS0ZzWVlqQ0l1aQozaXg2dmhFekVEclRMSWJ5VFYxYTNwcGRlSDlvbEpwenFHUXRqdFFhNTRUM3ltRnNXTzZzNTVpdTJGemcwZmtYClVESVVGeFI4RkVJeGlXNzUwc0ltRkJSNXFjN0k0U2E5dzdDOWs4azhScENaNDl2MGJaV2ZUWjhudkMrS2UrTngKYWkxRGhEdFJiWnpycStZV1hYTmZIZllaV0FlQXp6eGFyaWlWVXYyclYyQi9sUEVnSWJuZ0JYYTVWaGk0Lzl1eQpCbE81TTBLUHJRZXBYbTRVRzFXTHBnMkZyMkQzQURLZFJiRVlDODJud3VhVEhFdDc2NWtOUlI4dDZEST0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
  public.pem: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUNDZ0tDQWdFQXF1R0FNSEhpNGxwY0R5ZTY3T1loZGlCRHdHZ1hlQi9nTklFcVJFbVcrNlR6WTRnMm9ia0UKbnJBRUZWbjN0YVQySExGcEljV1JwZWhRdUs2ZTUzVnRTQWJYMklxTFRNWTR2R3hHWXVYcjZ6bHo1Vy96TitDawp0cVZFb2ZGQTZ2TkV4ZzFJREVkaFFleTFvV0draUgra0ZVRnlKM29pekYrQmxNaVNZZjRDY1YrUnhOUkozcTJFCk1SenROclptR0dlcER6MEJUV1g4SmlzaXdJNWdMbE5uTnFVcnZxMlN4aTVRNkFLQnB3M1lRdHQrcFFjSUVuY0sKYWVUN3JsRDdhcDNYeGx3bkU3NnFrVHQvOGd1NEIwU3FVK1hYSEtwWnZSa1d4Z01xcHBWUE9PbGhqNmRMME8wNgpwUDF6OVVxWkllTDUyTVZTY0UycHpjZnMrS3B2cHY0N3RFeXh5bDNZV3REMWVJU0ZOUm9GMy92ZTE3dmNVM2hEClVHSzVFa2M5eG9nVmJEdG9DQnBweFlRUlhiZmVVdm9Zcis3WmdoNFBZeHl4aDFTM1pMQXpiZFpZb2g3VTVkRG8KTWVFbWhaanRsMTRPM2UvRGg0NEdCL1pLYlZBR1ZMK0RRSGRFUVh2Y2Vpanp6b2xId2F4dlpVTjRwVTNJWVpmaQpJd25vZU9WMWI4WVJwNXdJd1JRNzlLTEIyKzlvSXJldGNaTDdKV1ZGTy9Hb2ZWUzJGTVJFeEdjMDR0SUVkSkhXCjM5R250M292VlE4dHY2Y0lYaWN4ZE00aWlHWHkrYUNLcFpxNVh1WnhoWDRMTXhLdU5UUVJTellxQ2QrdC9vV2YKcG1lajhNcnY2V3BROHBXSUluY25YUnV0dVlEK1NXeWtYMFo5R3FjRFRMa0ZWZmZEQXNYV0Y2OENBd0VBQVE9PQotLS0tLUVORCBSU0EgUFVCTElDIEtFWS0tLS0tCg==
  cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU4akNDQXRxZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFoTVFzd0NRWURWUVFHRXdKQ1VqRVMKTUJBR0ExVUVDaE1KUm05dlpGUnlZV05yTUI0WERUSTFNREl3TnpFMk1Ea3hNMW9YRFRJMk1ESXdOekUyTURreApNMW93SVRFTE1Ba0dBMVVFQmhNQ1FsSXhFakFRQmdOVkJBb1RDVVp2YjJSVWNtRmphekNDQWlJd0RRWUpLb1pJCmh2Y05BUUVCQlFBRGdnSVBBRENDQWdvQ2dnSUJBS3JoZ0RCeDR1SmFYQThudXV6bUlYWWdROEJvRjNnZjREU0IKS2tSSmx2dWs4Mk9JTnFHNUJKNndCQlZaOTdXazloeXhhU0hGa2FYb1VMaXVudWQxYlVnRzE5aUtpMHpHT0x4cwpSbUxsNitzNWMrVnY4emZncExhbFJLSHhRT3J6Uk1ZTlNBeEhZVUhzdGFGaHBJaC9wQlZCY2lkNklzeGZnWlRJCmttSCtBbkZma2NUVVNkNnRoREVjN1RhMlpoaG5xUTg5QVUxbC9DWXJJc0NPWUM1VFp6YWxLNzZ0a3NZdVVPZ0MKZ2FjTjJFTGJmcVVIQ0JKM0NtbmsrNjVRKzJxZDE4WmNKeE8rcXBFN2YvSUx1QWRFcWxQbDF4eXFXYjBaRnNZRApLcWFWVHpqcFlZK25TOUR0T3FUOWMvVkttU0hpK2RqRlVuQk5xYzNIN1BpcWI2YitPN1JNc2NwZDJGclE5WGlFCmhUVWFCZC83M3RlNzNGTjRRMUJpdVJKSFBjYUlGV3c3YUFnYWFjV0VFVjIzM2xMNkdLL3UyWUllRDJNY3NZZFUKdDJTd00yM1dXS0llMU9YUTZESGhKb1dZN1pkZUR0M3Z3NGVPQmdmMlNtMVFCbFMvZzBCM1JFRjczSG9vODg2SgpSOEdzYjJWRGVLVk55R0dYNGlNSjZIamxkVy9HRWFlY0NNRVVPL1Npd2R2dmFDSzNyWEdTK3lWbFJUdnhxSDFVCnRoVEVSTVJuTk9MU0JIU1IxdC9ScDdkNkwxVVBMYituQ0Y0bk1YVE9Jb2hsOHZtZ2lxV2F1VjdtY1lWK0N6TVMKcmpVMEVVczJLZ25mcmY2Rm42Wm5vL0RLNytscVVQS1ZpQ0ozSjEwYnJibUEva2xzcEY5R2ZScW5BMHk1QlZYMwp3d0xGMWhldkFnTUJBQUdqTlRBek1BNEdBMVVkRHdFQi93UUVBd0lGb0RBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGCkJRY0RBVEFNQmdOVkhSTUJBZjhFQWpBQU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQUtIM3lrUStabmZlK2QKc1llTlpCSWhneXVxUXJXOXpxSHhuc25aSjdNZGpsRE5nWEVldEl3SFRZYks5aTdCTzVqQU5lT1o4VHlrTHB4WAptMjJkbW50aXRjU1hSUG00bzNpaU9mcHhCYzlqNlkxZ29jb0xjSzNrRUdLY204NC92ekQySXM3M2gzbHY3WUZOClczanQzSXpUbjFHS2IzYWViMHNZd0xxUDl6aTh3UEVIUXgrUTNXQk1PSDlwejRvUFI2bGFRbVlPMG5rZzJXOEIKTmd3NGZQRWZvOXN6QndHUnlUaGhKRUpvUFhEUlc1U2dZbVFicVlmTzVwcnJQbVhrdGt0RERpMVNaaFBWUmxtQwpoLzRKUWw2UzQ0SHl6aFgzYm1NeERwSXFvOVZySDNSeTBrSzliZlB4UTRwU2NsNDcxLysyWFFRejZkTVJGcEI2CnRudnJvNXdFTVNhNE5QYkRyRWZjUTRaK3BDRVExS3hTVnJSeHBCMjBaaXV0bEJKR0pWclk1cDBYdUVqQ3d3NW0KTVdxa0R0dE9Cc3BLOHByWDNsckN5ZEdkT3dFR0NMdWRkYThyTHZXYzA5Mlh4VWVkbWdsb2pRckpyNElFMFVaUgo2R1c2QkJycFhueG45MURCSXZhMEJzZUxnbC9KSVRKdENtUVV6VS9GeStvNnRRSFgrTXRzMGMrMG82SFR2VGoxCm5WeGMvQjNBczZUa281NXFIZVRQR2Z2N3NMQmRsUE90d0tDYzJKblgzWExadEpJSjNiWkxkUUVmYW9jYkRqRHMKbzk1VkJOcWFZdmhqNjMzMVlPZ0FOMk1wbUtodmRMWVJMZ0NCVC9WekJOTjRiRWxVdFJVdGI0N2hScWFhVXRmaQpUUk50aE82QXkyYzZqV3owS0lMeXVzMXVNQTduSEE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: easy-cook-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "api.finditbuy.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: auto-landing-page-virtualservice
spec:
  hosts:
  - "api.finditbuy.com"
  gateways:
  - easy-cook-gateway
  http:
  - route:
    - destination:
        host: auto-landing-page
        port:
          number: 3000
