name: Docker Build and Push to Harbor

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: secret
        run: echo ${{ secrets.HARBORUSER }} ${{ secrets.HARBORPASS }}

      - name: Login to Harbor Registry
        uses: docker/login-action@v2
        with:
          registry: harbor.gambiarras.website
          username: ${{ secrets.HARBORUSER }}
          password: ${{ secrets.HARBORPASS }}
      
      - name: Build and tag Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: harbor.gambiarras.website/automate/auto-landing-page:${{ github.run_number }}
          load: true
      
      - name: Push Docker image to Harbor
        run: |
          docker push harbor.gambiarras.website/automate/auto-landing-page:${{ github.run_number }}
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
