name: Podman Build and Push to Harbor

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman
          podman --version
      
      - name: Set up Podman config for insecure registry
        run: |
          sudo mkdir -p /etc/containers/registries.conf.d/
          echo '[registries.insecure]
          registries = ["harbor.gambiarras.website"]' | sudo tee /etc/containers/registries.conf.d/insecure.conf
      
      - name: Login to Harbor Registry with Podman
        run: |
          podman login harbor.gambiarras.website -u ${{ secrets.HARBORUSER }} -p ${{ secrets.HARBORPASS }}
      
      - name: Build image with Podman
        run: |
          podman build ./ -t harbor.gambiarras.website/automate/auto-landing-page:latest
      
      - name: Push image with Podman
        run: |
          podman push harbor.gambiarras.website/automate/auto-landing-page:latest