name: Podman Build and Push to Harbor

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman
          podman --version
      
      - name: Login to Harbor Registry with Podman
        run: |
          podman login npx.finditbuy.com -u ${{ secrets.HARBORUSER }} -p ${{ secrets.HARBORPASS }}
      
      - name: Build image with Podman
        run: |
          podman build ./ -t npx.finditbuy.com/automate/auto-landing-page:latest
      
      - name: Push image with Podman
        run: |
          podman push npx.finditbuy.com/automate/auto-landing-page:latest